language: php

env:
  global:
  - DB=mysql
  - PHPUNIT_FLAGS='--no-coverage'
  - TEST_COVERAGE=0

services:
  - mysql

# https://phpunit.de/supported-versions.html
matrix:
  include:
  - php: 5.6
    env: PHPUNIT_VERSION=5.7.*
  - php: 7.0
    env: PHPUNIT_VERSION=6.5.*
  - php: 7.1
    env: PHPUNIT_VERSION=7.5.*
  - php: 7.2
    env: PHPUNIT_VERSION=7.5.*
  - php: 7.3
    env: PHPUNIT_VERSION=7.5.*
  - php: 7.4
    env: PHPUNIT_VERSION=7.5.* TEST_COVERAGE=1 PHPUNIT_FLAGS='--coverage-clover clover.xml'
  - php: nightly
    env: PHPUNIT_VERSION=7.5.*
  fast_finish: true
  allow_failures:
  - php: nightly

cache:
  apt: true
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

install:
  # Speed up build time by disabling Xdebug unless actually needed.
  - if [ "$TEST_COVERAGE" != '1' ]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
  - composer global require hirak/prestissimo --no-suggest --no-interaction
  # Update tests/composer.json to overwrite phpunit with specific version
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" -d ./tests --dev --no-update --no-interaction --no-suggest
  - composer install -d ./tests --no-suggest --no-interaction

before_script:
  - mysql --version
  - git clone git://github.com/ozh/YOURLS-fr_FR.git user/languages/fr
  - cp user/languages/fr/fr_FR.* user/languages
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp tests/data/config/yourls-tests-config-travis.php user/config.php

script: tests/vendor/bin/phpunit --configuration ./phpunit-travis.xml.dist $PHPUNIT_FLAGS

after_script:
  - |
    if [ "$TEST_COVERAGE" == '1' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar;
      travis_retry php ocular.phar code-coverage:upload --format=php-clover clover.xml;
    fi

notifications:
  email: false
